### ISSUE TITLE
compile error on gcc-7.5

### ISSUE THREAD

**Issue by beyou923** [alibaba/overlaybd#48]
[root@xxx build]# make
[  1%] Building CXX object src/CMakeFiles/image_lib.dir/bk_download.cpp.o
In file included from /home/container-acc/overlay-tcmu/overlaybd/src/overlaybd/alog-stdstring.h:19:0,
                 from /home/container-acc/overlay-tcmu/overlaybd/src/bk_download.cpp:22:
/home/container-acc/overlay-tcmu/overlaybd/src/overlaybd/string_view.h:29:36: fatal error: experimental/string_view: No such file or directory
 #include <experimental/string_view>
                                    ^
compilation terminated.
make[2]: *** [src/CMakeFiles/image_lib.dir/bk_download.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/image_lib.dir/all] Error 2
make: *** [all] Error 2

**Comment by liulanzheng** [comment]
@beyou923 please show me the detail info of your gcc.

**Comment by beyou923** [comment]
the following is my gcc detail info
`[root@xxx]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/7.5.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../configure --enable-languages=c,c++ --disable-multilib
Thread model: posix
gcc version 7.5.0 (GCC)
`

**Comment by liulanzheng** [comment]
@beyou923 I tried for gcc-7.5.0 and it worked.  The problems seems that something wrong about your gcc configure  ` ../configure --enable-languages=c,c++ --disable-multilib`. It may result the gcc `include` out of  your system path so that `experimental/string_view` can not be found.

**Comment by beyou923** [comment]
@liulanzheng can you share your gcc config?

**Comment by liulanzheng** [comment]
@beyou923 
 ../configure --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --enable-gnu-indirect-function --with-tune=generic --disable-multilib -prefix=/usr

This is copied from other place. And I used this configure to compile gcc and worked well.

**Comment by beyou923** [comment]
@liulanzheng  Thanks you for your help. I successfully compiled overlaybd.
