### ISSUE TITLE
需要镜像中心和Node都安装吗？

### ISSUE THREAD

**Issue by CuZn13** [alibaba/overlaybd#6]
使用overlaybd做镜像的按需拉取，需要镜像中心所在的物理机也安装配置overlaybd相关组件吗？

**Comment by beef9999** [comment]
No, the image registry could be standard release version, no extra software need to be installed.

P.S. If you have run the example (https://github.com/alibaba/accelerated-container-image/blob/main/docs/EXAMPLES.md), you may noticed that we provided a public Image Registry for test. No auth is required in this repo.

**Comment by beef9999** [comment]
Also, we recommend English communication in this project, considering there might be developers from different countries. @CuZn13
